context:
  version: "1.5.0"


package:
  name: libgit2
  version: "{{ version }}"

source:
  url: https://github.com/libgit2/libgit2/archive/refs/tags/v{{ version }}.zip

build:
  number: 0

requirements:
  build:
    - "{{ compiler('c') }}"

